# Global configuration
# Values in this configuration file will be exported as environment variables
# in init.sh in the form PARENT_LEAF=value, for example:
# api: name: test -> API_NAME=test
---
debug: True
production: False

cluster:
  name: test
  config_file: kube_config.yaml
  api_port: 6550

api:
  cluster:
    namespace: api
  domain: sample.k3d.localhost  # Can only be defined in local deployment
  https_port: 8080
  redirect_url: https://sample.k3d.localhost:8080/oauth2/callback
  src_directory: /src  # Can only be defined in local deployment
  image:
    name: test-api
    tag: local

azure:
  tenant_id: __CHANGE_ME__
  subscription_id: __CHANGE_ME__
  suffix: __CHANGE_ME__   # Required for AKS
  acr_name: __CHANGE_ME__   # Required for AKS
  app_registration:
    name: sample-k3d-localhost

opa:
  root_email: __CHANGE_ME__@__CHANGE_ME__

aws:
  prefix: sample-k3d-__CHANGE_ME__
  profile: __CHANGE_ME__
