# Global configuration
# Values in this configuration file will be exported as environment variables
# in init.sh in the form PARENT_LEAF=value, for example:
# api: name: test -> API_NAME=test
---
debug: True
production: False

cluster:
  name: test
  config_file: kube_config.yaml
  api_port: 6550

api:
  cluster:
    namespace: api
  http_port: 8080
  image_name: test-api
  image_tag: local

# ssl_cert_filename: localhost.crt
# ssl_key_filename: localhost.key
