{{- $app := .Release.Name -}}
{{- $component := "web" -}}
{{- $name := printf "%s-%s" $app $component -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $name }}"
  labels:
    app: "{{ $app }}"
    component: "{{ $component }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ $app }}"
      component: "{{ $component }}"
  template:
    metadata:
      labels:
        app: "{{ $app }}"
        component: "{{ $component }}"
    spec:
      containers:
        - name: "{{ $component }}"
          image: "{{ .Values.app.image }}"
          imagePullPolicy: Never
          env:
            - name: PRODUCTION
              value: "{{ .Values.app.production }}"
            - name: DEBUG
              value: "{{ .Values.app.debug }}"
            - name: API_PORT
              value: "{{ .Values.app.port }}"
            - name: OPA_URL
              value: "http://opa.{{ .Values.namespace }}.svc.cluster.local"
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
        - name: "nginx"
          image: nginx:latest
          ports:
            - name: nginx-http
              containerPort: {{ .Values.nginx.port }}
              protocol: TCP
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/
              readOnly: true
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
