{{- $name := .Release.Name -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ $name }}
  labels:
    app:  {{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.opa.port }}
      protocol: TCP
      name: http
  selector:
    app: "{{ $name }}"
